### PR TITLE
Exposing rename on file system

### PR DESCRIPTION
**Pull request by cmercur2**

### CODE REVIEW

**Comment by s-macke** [comment]
Thanks, looks good. May I ask you about the goal of these changes? Do you want to add a filesystem browser?

**Comment by cmercur2** [comment]
Yes sir, we are working on the cs-education/sysbuild to add a project explorer and a persistent file system based on the local storage.

**Comment by cmercur2** [comment]
Also I we've unintentionally merged commits that shouldn't be merged. 
The only files that should have been commited are the two filesystem.js files.

I apologize for that.

**Comment by s-macke** [comment]
Cool. I hope you will manage it. 
When you add more message commands you might want to set "fs." (for example "fs.rename") or something similar in front of all filesystem commands.

**Pull request merged**
