### PR TITLE
refactoring: created facade for CPU implementations + tests

### PR DESCRIPTION
**Pull request by regular**
Moved CPU creation/implementation switching code from worker/system.js to worker/cpu/index.js.

You can now

    var CPU = require('./cpu');
    var myFastCPU = new CPU('asm", myRAM, myHeap, ncores);

without having to care about the details.

Additionally, I added a simple test for the three CPU implementations that run in node.
The tests create a CPU of each kind, load some values into two registers, write an add instruction to RAM and start the CPU for a single instruction. Then they check the value of the result register.

You can run these test with

    npm test

it should give you
✔ 1) safe CPU can add two 32 bit registers (4 ms)
✔ 2) asm CPU can add two 32 bit registers (7 ms)
✔ 3) smp CPU can add two 32 bit registers (2 ms)

Don't forget to install the dev dependencies (lab and expect) by running

    npm install

Also fixed a crashing bug when no framebuffer exists.

### CODE REVIEW

**Comment by regular** [comment]
Wait a second, I missed something essential .... (all three tests create the 'safe' cpu)

**Comment by regular** [comment]
Now the correct CPUs are created and tested. The result:

* the safe cpu works as expected
* the SMP cpu produces the wrong result (0)
* the asm CPU hangs in Step()

Did I miss something in the test setup?

**Comment by regular** [comment]
Did some debugging. Looks like the SMP implementation does not actually perform an instruction when called with Step(1,1)
I'll investigate further tomorrow.

**Comment by s-macke** [comment]
Indeed, to patch the global Math object is bad habit.
We can give each CPU their own imul implementation.

**Comment by s-macke** [comment]
the IPS statistics is not working anymore

**Comment by s-macke** [comment]
merged and I fixed the error. The return value was not returned.

**Comment by regular** [comment]
test/cpu-facade fixed in #54

**Pull request merged**
