### PR TITLE
Add functionality for watching file writes and reading/writing files via file system

### PR DESCRIPTION
**Pull request by emnh**
Hi,

I added some functionality for watching file writes and reading/writing files via file system.
I want to use this to integrate jor1k with [JSBin](http://jsbin.com/), so that the user can edit html,js,css files with vim in jor1k and then the UI will update itself when the user writes the files to the linux file system.

The new file watch.html is just a demo of the changes and is not really needed.
It is mostly identical to main.html.

### CODE REVIEW

**Comment by emnh** [comment]
I have a [working demo](http://alexis.lart.no:3000/?html,js,vim,output) of Native Vim integration with JSBin running under [jor1k](http://github.com/s-macke/jor1k/) linux RISC emulation. That's the end result what I wanted to achieve with this patch.

**Comment by s-macke** [comment]
The binary of vim is in principle compiled with most of the features. I just removed the 30MB of data including the data for syntax highlightning.

cd src/vim; make install DESTDIR=$(RAMFS)
        rm -rf $(RAMFS)/usr/share/vim/vim74/lang
        rm -rf $(RAMFS)/usr/share/vim/vim74/doc
        rm -rf $(RAMFS)/usr/share/vim/vim74/tutor
        rm -rf $(RAMFS)/usr/share/vim/vim74/spell
        rm -rf $(RAMFS)/usr/share/vim/vim74/syntax
        rm -rf $(RAMFS)/usr/share/vim/vim74/ftplugin
        rm -rf $(RAMFS)/usr/share/vim/vim74/compiler
        rm -rf $(RAMFS)/usr/share/vim/vim74/tools
        rm -rf $(RAMFS)/usr/share/vim/vim74/autoload
        rm -rf $(RAMFS)/usr/share/vim/vim74/indent
        rm -rf $(RAMFS)/usr/share/vim/vim74/macros
        rm -rf $(RAMFS)/usr/share/vim/vim74/keymap
        rm -rf $(RAMFS)/usr/share/vim/vim74/plugin

**Comment by s-macke** [comment]
This is one feature, which I wanted to add since a long time. Thanks. 

Next time, don't include the browserified -min files in the commit. I would like to keep them separated.

**Comment by emnh** [comment]
Thanks!

Ah ok.. I saw in the logs that /usr/share files for vim are not requested by the default load of vim anyway. I actually want to add _more_ features to vim, including syntax highlighting, so I will install the cross compiler chain. I want to see how slow it gets if it's still bearable.

I actually tried with Norwegian characters øæå before and it seemed to work fine. I was thinking about using UTF8Stream class, but figured since it seemed to work that it wasn't necessary. I based my code for this on [StackOverflow](http://stackoverflow.com/questions/17191945/conversion-between-utf-8-arraybuffer-and-string). Should have left the URL in the code. Do you have any example characters that are not working?

Vim is not compiled with multi-byte support though so the character offsets are wrong in the edit window making text overlap.

**Comment by s-macke** [comment]
What I wanted to say is, that you don't have to recompile vim. If you just insert the correct data files it should work. The problem is not necessarily the speed of the emulator. 
The reason is, to keep the filesystem small for github. Without deleting all those stuff, the filesystem would already exceed the limit of 1GB for github repositories. Additionally the filesystem json file would explode. 
However, the story is different if I know that a certain feature is really used. I won't include all 30MB in the official filesystem, but a small amount of the most important files is possible.
I deleted everything, because I never used vim. So I don't know, which data files are the most important.

I will test your new filesystem commands when I move the filesystem interface stuff to it's own class. 
It has also other flaws and inconsistencies.

**Comment by regular** [comment]
@emnh, wow, that's neat!
I am also interested in a wide vim feature set and the the watch functionality is very handy for educational stuff, like integration into an interactive tutorial (that's my use case)

Your demo currently crashes (unknown partition table)

**Comment by s-macke** [comment]
vim is compiled with the following options: 
--disable-xsmp --disable-netbeans --disable-acl --with-tlib=ncurses --enable-gui=no --without-x --with-features=small

Here is the link to the vim package without removed files:
jor1k.com/vim.tar.bz2

It would be great, if someone would tell me, which files I can safely remove. 
I guess for 99% of the mostly used features you need only 10% of the files.
I don't think, that we need the game hanoi in vim or the belarusian-jcuken.keymap.

**Comment by emnh** [comment]
I think you can remove all those files for the time being, as none of them are used by a default load of vim as far as I saw in Chrome network logs, but at the very least it would be nice to have syntax files for common programming languages. I will let you know later if I customize my own version what I figure out that is good to have. I will probably just host my own version with all the files so I don't have to worry about optimizing the set.

You could also run "strace -e open vim 2>&1 | fgrep /usr/share/vim file.c"  on a couple of common files to see what files are used. Or watch Chrome network tab in developer tools when loading vim in jor1k.

**Comment by s-macke** [comment]
Indeed, The --features-small option does not contain syntax highlightning
http://www.drchip.org/astronaut/vim/vimfeat.html

**Comment by s-macke** [comment]
I have updated vim and included syntax highlighting for a few file formats.

**Pull request merged**
